version: 3.15.1.{build}
configuration: AppVeyor
os: Visual Studio 2015
branches:
  only:
    - master
    - dev
platform:
- x64
- x86
before_build:
- cmd: nuget restore
build:
  project: SoundSwitch.sln
  parallel: true
  verbosity: minimal
install:
  git submodule update --init --recursive
test:
  categories:
    except:
    - AudioDevice
  assemblies: 
   - '**\x64\$(configuration)\*.tests.dll'
   - '**\x86\$(configuration)\*.tests.dll'